add missing #include
Build error with Qt-5.15.0 is:

/home/grg/aur/slim-simulator/src/SLiM/QtSLiM/QtSLiMGraphView_SubpopFitnessDists.cpp: In member function ‘virtual void QtSLiMGraphView_SubpopFitnessDists::drawGraph(QPainter&, QRect)’:
/home/grg/aur/slim-simulator/src/SLiM/QtSLiM/QtSLiMGraphView_SubpopFitnessDists.cpp:138:26: error: aggregate ‘QPainterPath linePath’ has incomplete type and cannot be defined
  138 |             QPainterPath linePath;
      |                          ^~~~~~~~
/home/grg/aur/slim-simulator/src/SLiM/QtSLiM/QtSLiMGraphView_SubpopFitnessDists.cpp:160:18: error: aggregate ‘QPainterPath linePath’ has incomplete type and cannot be defined
  160 |     QPainterPath linePath;
      |                  ^~~~~~~~